name: Publish

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: npm install, compile, lint
      run: |
        npm install
        npm run compile
        npm run lint
    - name: test
      if: github.branch == 'qwerty'
      run: |
        export DISPLAY=':99.0'
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        npm test
    - name: publish
      run: |
        #./node_modules/vsce/out/vsce publish -p ${{ secrets.VSCE_TOKEN }} minor
        git checkout master
        echo "q" > text.txt
        git add .
        git status
    - name: push
      uses: elstudio/actions-js-build/commit@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUSH_BRANCH: 'master'


      
